const express = require('express');
const { verifyToken, requireRole } = require('../middleware/auth');
const { ROLES } = require('../config/constants');
const Campaign = require('../models/Campaign');
const Webhook = require('../models/Webhook');
const Ledger = require('../models/Ledger');

const router = express.Router();

// Merchants, NGO staff and admins may manage campaigns.
router.use(verifyToken, requireRole(ROLES.MERCHANT, ROLES.NGO_STAFF, ROLES.ADMIN));

function resolveNgoId(req) {
  if (req.user.role === ROLES.ADMIN && req.query.ngoId) {
    return req.query.ngoId;
  }
  return req.user.ngoId;
}

function buildCheckoutUrl(req, campaignId) {
  const base =
    process.env.CHECKOUT_BASE_URL ||
    `${req.protocol}://${req.get('host')}/donate`;
  return `${base}/${campaignId}`;
}

/**
 * GET /api/merchant/campaigns — campaigns for this NGO.
 */
router.get('/campaigns', async (req, res, next) => {
  try {
    const campaigns = await Campaign.find({ ngoId: resolveNgoId(req) }).sort({
      createdAt: -1,
    });
    return res.json({ success: true, data: campaigns });
  } catch (err) {
    return next(err);
  }
});

/**
 * POST /api/merchant/campaigns
 * Body: { name, description, targetAmount }
 * Creates a campaign with a unique checkout URL.
 */
router.post('/campaigns', async (req, res, next) => {
  try {
    const { name, description, targetAmount } = req.body;
    if (!name) {
      return res.status(400).json({ success: false, message: 'name is required' });
    }

    const ngoId = resolveNgoId(req);
    if (!ngoId) {
      return res
        .status(400)
        .json({ success: false, message: 'No NGO associated with this user' });
    }

    // Create first (campaignId is generated by the model default), then
    // attach the checkout URL derived from that id.
    let campaign = await Campaign.create({
      ngoId,
      name,
      description: description || '',
      targetAmount: Number(targetAmount) || 0,
    });

    const checkoutUrl = buildCheckoutUrl(req, campaign.campaignId);
    campaign.checkoutUrl = checkoutUrl;
    await campaign.save();

    return res.status(201).json({ success: true, campaign, checkoutUrl });
  } catch (err) {
    return next(err);
  }
});

/**
 * GET /api/merchant/donations/:campaignId — verified donations for a campaign.
 * Resolves donor intents (webhooks) for the campaign, then their ledger entries.
 */
router.get('/donations/:campaignId', async (req, res, next) => {
  try {
    const ngoId = resolveNgoId(req);

    const campaign = await Campaign.findOne({
      campaignId: req.params.campaignId,
      ngoId,
    });
    if (!campaign) {
      return res.status(404).json({ success: false, message: 'Campaign not found' });
    }

    const webhooks = await Webhook.find({
      ngoId,
      campaignId: req.params.campaignId,
    }).select('_id');
    const webhookIds = webhooks.map((w) => w._id);

    const donations = await Ledger.find({
      ngoId,
      webhookId: { $in: webhookIds },
    }).sort({ createdAt: -1 });

    return res.json({
      success: true,
      data: { campaign, donations },
    });
  } catch (err) {
    return next(err);
  }
});

module.exports = router;
