const mongoose = require('mongoose');
const { DEVICE_STATUS } = require('../config/constants');

const deviceSchema = new mongoose.Schema(
  {
    // Android device id used as the stable identifier from the APK.
    deviceId: { type: String, default: '', unique: true, index: true },
    // Opaque token the device presents on the deviceToken header to post events.
    deviceToken: { type: String, default: '', index: true },
    // Short human-typeable pairing code generated by the trader panel before
    // a phone exists, and consumed by /register-device to claim this row.
    licenseKey: { type: String, default: '', index: true },
    // Pairing code expiry (5 min from generation). Only meaningful while
    // status === PENDING — /register-device rejects a claim attempt past
    // this, whether it's a fresh scan or a retry against a stale code.
    licenseExpiresAt: { type: Date, default: null },
    // DEPRECATED (2026-08-06): superseded by traderId below, which is the
    // real authorization boundary now. NOT dead — still read by apk.js
    // (stamped onto RawEvent.ngoId, and copied onto DebitSMS/OverlayCapture/
    // OutgoingPayment) to feed the not-yet-retired donation-ledger matching
    // path (matchingEngine.checkMatch) and payoutVerifier.js. Do not drop
    // without first retiring/rekeying those.
    ngoId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'NGO',
      default: null,
      index: true,
    },
    // The real trader (MySQL trader.id) who generated this device's pairing
    // code — the actual authorization boundary going forward, same as
    // Account.traderId.
    traderId: {
      type: Number,
      default: null,
      index: true,
    },
    deviceModel: { type: String, default: '' },
    // Trader-assigned display name (set via SetDeviceNameActivity), distinct
    // from deviceModel (the hardware model string).
    deviceName: { type: String, default: '' },
    androidVersion: { type: String, default: '' },
    appVersion: { type: String, default: '' },
    status: {
      type: String,
      enum: Object.values(DEVICE_STATUS),
      default: DEVICE_STATUS.ACTIVE,
    },
    lastSeen: { type: Date, default: Date.now },
    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Device', deviceSchema);
