const mongoose = require('mongoose');
const { DEVICE_STATUS } = require('../config/constants');

const deviceSchema = new mongoose.Schema(
  {
    // Android device id used as the stable identifier from the APK.
    deviceId: { type: String, default: '', unique: true, index: true },
    // Opaque token the device presents on the deviceToken header to post events.
    deviceToken: { type: String, default: '', index: true },
    // Short human-typeable pairing code generated by the trader panel before
    // a phone exists, and consumed by /register-device to claim this row.
    licenseKey: { type: String, default: '', index: true },
    // Pairing code expiry (5 min from generation). Only meaningful while
    // status === PENDING — /register-device rejects a claim attempt past
    // this, whether it's a fresh scan or a retry against a stale code.
    licenseExpiresAt: { type: Date, default: null },
    // DEPRECATED (2026-08-06): superseded by traderId below, which is the
    // real authorization boundary now. NOT dead — still read by apk.js
    // (stamped onto RawEvent.ngoId, and copied onto DebitSMS/OutgoingPayment)
    // to feed the not-yet-retired donation-ledger matching path
    // (matchingEngine.checkMatch). Do not drop without first retiring/
    // rekeying that.
    ngoId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'NGO',
      default: null,
      index: true,
    },
    // The real trader (MySQL trader.id) who generated this device's pairing
    // code — the actual authorization boundary going forward, same as
    // Account.traderId.
    traderId: {
      type: Number,
      default: null,
      index: true,
    },
    // Third status field, separate from the lastSeen-derived `online` check
    // (routes/apk.js's isOnline()) — reported by HeartbeatService from
    // ListenerHealthStore, itself set by NotificationService's
    // onListenerConnected/onListenerDisconnected. null = never reported
    // (older APK build predating this field, or no heartbeat yet) — must
    // stay distinct from `false` so the trader panel doesn't show "degraded"
    // for a device that simply hasn't said anything either way.
    listenerConnected: { type: Boolean, default: null },
    // FEATURE 2 — Payout evidence capture. Set via POST
    // /api/internal/set-active-payout (the P2P backend, once a trader picks
    // up a payout order) and cleared the same way. Mirrored down to the
    // device on every heartbeat response — see routes/apk.js.
    activePayout: { type: mongoose.Schema.Types.Mixed, default: null },
    deviceModel: { type: String, default: '' },
    // Trader-assigned display name (set via SetDeviceNameActivity), distinct
    // from deviceModel (the hardware model string).
    deviceName: { type: String, default: '' },
    androidVersion: { type: String, default: '' },
    appVersion: { type: String, default: '' },
    status: {
      type: String,
      enum: Object.values(DEVICE_STATUS),
      default: DEVICE_STATUS.ACTIVE,
    },
    lastSeen: { type: Date, default: Date.now },
    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Device', deviceSchema);
